const actionTypes = {
    NEW_ARTICLE_REQUEST: '@@article/NEW_ARTICLE_REQUEST',
    NEW_ARTICLE_SUCCESS: '@@article/NEW_ARTICLE_SUCCESS',
    NEW_ARTICLE_ERROR: '@@article/NEW_ARTICLE_ERROR',
    ALL_ARTICLES_REQUEST: '@@article/ALL_ARTICLES_REQUEST',
    ALL_ARTICLES_SUCCESS: '@@article/ALL_ARTICLES_SUCCESS',
    ALL_ARTICLES_ERROR: '@@article/ALL_ARTICLES_ERROR',
    FETCH_SINGLE_ARTICLE_REQUEST: '@@article/FETCH_SINGLE_ARTICLE_REQUEST',
    FETCH_SINGLE_ARTICLE_SUCCESS: '@@article/FETCH_SINGLE_ARTICLE_SUCCESS',
    FETCH_SINGLE_ARTICLE_ERROR: '@@article/FETCH_SINGLE_ARTICLE_ERROR'
};

export default actionTypes;
