export default {
    FETCH_ARTICLES_REQUEST: '@@article/FETCH_ARTICLES_REQUEST',
    FETCH_ARTICLES_SUCCESS: '@@article/FETCH_ARTICLES_SUCCESS',
    FETCH_ARTICLES_ERROR: '@@article/FETCH_ARTICLES_ERROR'
};
