export default {
    FETCH_ARTICLES_REQUEST: '@@article/FETCH_ARTICLES_REQUEST',
    FETCH_ARTICLES_SUCCESS: '@@article/FETCH_ARTICLES_SUCCESS',
    FETCH_ARTICLES_ERROR: '@@article/FETCH_ARTICLES_ERROR',

    FETCH_SINGLE_ARTICLE_REQUEST: '@@article/FETCH_SINGLE_ARTICLE_REQUEST',
    FETCH_SINGLE_ARTICLE_SUCCESS: '@@article/FETCH_SINGLE_ARTICLE_SUCCESS',
    FETCH_SINGLE_ARTICLE_ERROR: '@@article/FETCH_SINGLE_ARTICLE_ERROR',

    CREATE_ARTICLE_REQUEST: '@@article/CREATE_ARTICLE_REQUEST',
    CREATE_ARTICLE_SUCCESS: '@@article/CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLE_ERROR: '@@article/CREATE_ARTICLE_ERROR'
};
