export default {
    INIT_APP: '@@app/INIT_APP',

    REGISTER_USER: '@@app/REGISTER_USER',
    LOGIN_USER: '@@app/LOGIN_USER',
    LOGOUT_USER: '@@app/LOGOUT_USER',

    FETCH_ARTICLES: '@@app/FETCH_ARTICLES',
    FETCH_ARTICLE: '@@app/FETCH_ARTICLE',
    CREATE_NEW_ARTICLE: '@app/CREATE_NEW_ARTICLE'
};
